import 'dotenv/config';

import { AppDataSource } from '../data-source';
import { HydraHead } from '../../hydra-heads/entities/HydraHead.entity';
import { HydraNode } from '../../hydra-main/entities/HydraNode.entity';
import { getKeyPairFromMnemonic } from '../../common/utils/cardano-core';

async function main() {
    console.log('Starting party to head migration seeder...');

    const dataSource = AppDataSource;
    await dataSource.initialize();

    await dataSource.transaction(async transactionalEntityManager => {
        const parties = await transactionalEntityManager
            .getRepository('HydraParty')
            .find({ relations: ['hydraNodes', 'hydraNodes.cardanoAccount'] });

        console.log(`Found ${parties.length} parties to process`);

        for (const party of parties) {
            console.log(`\nProcessing party ID: ${party.id}`);
            const countNode = party.hydraNodes.length;

            // Tạo head
            const head = transactionalEntityManager.getRepository(HydraHead).create({
                nodes: countNode,
                contestationPeriod: '120',
                depositPeriod: '720',
                persistenceRotateAfter: '15000',
            });
            const savedHead = await transactionalEntityManager.save(HydraHead, head);
            console.log(`  ✓ Created head ID: ${savedHead.id}`);

            // Lọc nodes hợp lệ
            const validNodes = party.hydraNodes.filter(node => node.cardanoAccount);

            if (validNodes.length === 0) {
                continue;
            }

            // Cập nhật nodes
            validNodes.forEach(node => {
                try {
                    const keyPair = getKeyPairFromMnemonic(node.cardanoAccount.mnemonic);

                    node.skey = transformerKey(keyPair.skey);
                    node.vkey = transformerKey(keyPair.vkey);
                    node.cardanoSKey = keyPair.skey;
                    node.cardanoVKey = keyPair.vkey;
                    node.hydraHead = savedHead;
                    node.description = `Generated by head ${savedHead.id}`;
                } catch (error) {
                    throw new Error(`Failed to generate keypair for node ${node.id}: ${error.message}`);
                }
            });

            // Bulk save trong transaction
            await transactionalEntityManager.save(HydraNode, validNodes);
            console.log(`  ✓ Updated ${validNodes.length}/${party.hydraNodes.length} nodes`);
        }
    });

    console.log('\n✅ Migration completed successfully!');
    await dataSource.destroy();
}

function transformerKey(key: string) {
    let cborHex: string;
    try {
        const parsed = JSON.parse(key);
        cborHex = parsed.cborHex ?? key;
    } catch {
        cborHex = key;
    }

    return cborHex;
}

main().catch(err => {
    console.error('Seeder failed:', err);
    process.exit(1);
});
