import crypto from 'crypto';

export const generateConsumerKey = () => {
    return crypto.randomBytes(16).toString('hex');
};

export function generateKeyFile(cborHex: String, typeKey: string): string {
    return JSON.stringify(
        {
            type: typeKey,
            description: 'Generated by Hexcore',
            cborHex: cborHex,
        },
        null,
        4,
    );
}
