import crypto from 'crypto';
import { TypeKey } from 'src/enums/type-key.enum';

export const generateConsumerKey = () => {
    return crypto.randomBytes(16).toString('hex');
};

export function generateKeyFile(cborHex: String, typeKey: TypeKey): string {
    return JSON.stringify({
        type: typeKey,
        description: 'Generated by Hexcore',
        cborHex: cborHex,
    }, null, 4);
}
